// Bluetooth debugs
#define DEBUG_BLE_DISPLAY_VOLTAGE 0
#define DEBUG_BLE_DISPLAY_ANALOG_BRAKE 0
#define DEBUG_BLE_DISPLAY_FRAME 0

// Serial general debugs
#define DEBUG_DISPLAY_BLE_SCAN 0
#define DEBUG_DISPLAY_BLE_NOTIFY 0
#define DEBUG_DISPLAY_SPEED 0
#define DEBUG_DISPLAY_MODE 0
#define DEBUG_DISPLAY_DIGITAL_BRAKE 0
#define DEBUG_DISPLAY_ANALOG_BRAKE 1
#define DEBUG_DISPLAY_ECO 0
#define DEBUG_DISPLAY_ACCEL 0
#define DEBUG_DISPLAY_NITRO 0
#define DEBUG_DISPLAY_BUTTON1 0
#define DEBUG_DISPLAY_BUTTON2 0
#define DEBUG_DISPLAY_VOLTAGE 0
#define DEBUG_DISPLAY_CURRENT 0
#define DEBUG_DISPLAY_DHT 0
#define DEBUG_DISPLAY_SPEED_PID 0

// Serial frame deconding debugs
#define DEBUG_DISPLAY_FRAME_LCD_TO_CNTRL 0
#define DEBUG_DISPLAY_FRAME_CNTRL_TO_LCD 0
#define DEBUG_DISPLAY_DECODED_FRAME_CNTRL_TO_LCD 0
#define DEBUG_SERIAL_CHECKSUM_LCD_TO_CNTRL 0
#define DEBUG_SERIAL_CHECKSUM_CNTRL_TO_LCD 0